name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ">=3.13"

      - name: Install uv
        run: pip install uv

      - name: Install project dependencies
        run: make sync

      - name: Prepare environment variables
        run: |
          echo "DEBUG=True" >> .env
          echo "SECRET_KEY=test-secret" >> .env
          echo "DATABASE_URL=sqlite:///$(pwd)/db.sqlite3" >> .env

      - name: Run migrations
        run: uv run python manage.py migrate

      - name: Run tests with coverage
        run: |
          uv pip install coverage pytest pytest-cov
          uv run pytest --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
