name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ">=3.13"

      - name: Install uv
        uses: yezz123/setup-uv@v4

      - name: Install project dependencies
        run: make sync

      - name: Run linters
        run: make lint

      - name: Run tests with coverage
        run: |
          uv run coverage run -m pytest
          uv run coverage report -m
          uv run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
